CREATE TABLE bankdetails (
    id SERIAL PRIMARY KEY,
    bank_name CHARACTER VARYING(100) NOT NULL,
    bank_code CHARACTER VARYING(20) NOT NULL,
    account_name CHARACTER VARYING(50) NOT NULL,
    account_number CHARACTER VARYING(20) NOT NULL,
    customer_id INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_customer_id_bankdetails FOREIGN KEY (customer_id) REFERENCES customer(id) DEFERRABLE INITIALLY DEFERRED
);
