// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"
)

type Admindatum struct {
	ID               int32          `json:"id"`
	BitpowrAccountID string         `json:"bitpowr_account_id"`
	BtcAddress       sql.NullString `json:"btc_address"`
	UsdtAddress      sql.NullString `json:"usdt_address"`
	UsdtTronAddress  sql.NullString `json:"usdt_tron_address"`
	AdminEmail       string         `json:"admin_email"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Coinswap struct {
	ID                 int32          `json:"id"`
	CoinName           string         `json:"coin_name"`
	CoinAmountToSwap   string         `json:"coin_amount_to_swap"`
	Network            string         `json:"network"`
	PhoneNumber        string         `json:"phone_number"`
	CoinAddress        string         `json:"coin_address"`
	TransactionRef     string         `json:"transaction_ref"`
	TransactionStatus  string         `json:"transaction_status"`
	CurrentUsdtNgnRate string         `json:"current_usdt_ngn_rate"`
	CustomerID         int32          `json:"customer_id"`
	NgnEquivalent      string         `json:"ngn_equivalent"`
	PayoutStatus       string         `json:"payout_status"`
	BankAccName        string         `json:"bank_acc_name"`
	BankAccNumber      string         `json:"bank_acc_number"`
	BitpowrRef         sql.NullString `json:"bitpowr_ref"`
	TransAddress       sql.NullString `json:"trans_address"`
	TransAmount        sql.NullString `json:"trans_amount"`
	TransChain         sql.NullString `json:"trans_chain"`
	TransHash          sql.NullString `json:"trans_hash"`
	BankCode           string         `json:"bank_code"`
	AdminTransAmount   sql.NullString `json:"admin_trans_amount"`
	AdminTransFee      sql.NullString `json:"admin_trans_fee"`
	AdminTransRef      sql.NullString `json:"admin_trans_ref"`
	AdminTransUid      sql.NullString `json:"admin_trans_uid"`
	TransAmountNgn     sql.NullString `json:"trans_amount_ngn"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Customer struct {
	ID              int32          `json:"id"`
	LastLogin       sql.NullTime   `json:"last_login"`
	Photo           sql.NullString `json:"photo"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	Phone           string         `json:"phone"`
	IsActive        bool           `json:"is_active"`
	IsStaff         bool           `json:"is_staff"`
	IsSupercustomer bool           `json:"is_supercustomer"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Customerasset struct {
	ID                 int32          `json:"id"`
	BtcNetwork         sql.NullString `json:"btc_network"`
	BtcAddress         sql.NullString `json:"btc_address"`
	BtcAddressUid      sql.NullString `json:"btc_address_uid"`
	UsdtNetwork        sql.NullString `json:"usdt_network"`
	UsdtAddress        sql.NullString `json:"usdt_address"`
	UsdtAddressUid     sql.NullString `json:"usdt_address_uid"`
	UsdtTronNetwork    sql.NullString `json:"usdt_tron_network"`
	UsdtTronAddress    sql.NullString `json:"usdt_tron_address"`
	UsdtTronAddressUid sql.NullString `json:"usdt_tron_address_uid"`
	UsdtBscNetwork     sql.NullString `json:"usdt_bsc_network"`
	UsdtBscAddress     sql.NullString `json:"usdt_bsc_address"`
	UsdtBscAddressUid  sql.NullString `json:"usdt_bsc_address_uid"`
	CustomerID         int32          `json:"customer_id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type Customerkyc struct {
	ID                 int32     `json:"id"`
	CountryOfResidence string    `json:"country_of_residence"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	ResidentialAddress string    `json:"residential_address"`
	GovtIDPhoto        string    `json:"govt_id_photo"`
	GovtIDNumber       string    `json:"govt_id_number"`
	GovtIDType         string    `json:"govt_id_type"`
	ExpiryDate         time.Time `json:"expiry_date"`
	SelfiePhoto        string    `json:"selfie_photo"`
	CustomerID         int32     `json:"customer_id"`
	KycVerified        string    `json:"kyc_verified"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Ratecalculator struct {
	ID               int32     `json:"id"`
	CoinName         string    `json:"coin_name"`
	CoinAmountToCalc string    `json:"coin_amount_to_calc"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Usdtngnrate struct {
	ID          int32     `json:"id"`
	UsdtNgnRate string    `json:"usdt_ngn_rate"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
