// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: usdtngnrate.sql

package db

import (
	"context"
)

const recentUsdtNgnRate = `-- name: RecentUsdtNgnRate :one
INSERT INTO usdtngnrate (
    usdt_ngn_rate
) VALUES (
    $1
) RETURNING id, usdt_ngn_rate, created_at, updated_at
`

func (q *Queries) RecentUsdtNgnRate(ctx context.Context, usdtNgnRate string) (Usdtngnrate, error) {
	row := q.db.QueryRowContext(ctx, recentUsdtNgnRate, usdtNgnRate)
	var i Usdtngnrate
	err := row.Scan(
		&i.ID,
		&i.UsdtNgnRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
